[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "ninja; sys_platform != 'win32'",
    "cmake>=3.12",
    "pybind11>=2.6.1",
    "numpy>=1.16.2",
    "pandas>=1.0.5",
    "seaborn>=0.11.0",
    "iteround>=1.0.2",
    "matplotlib>=3.2.2",
]

build-backend = "setuptools.build_meta"
